### ISSUE TITLE
Upgrade dependency version

### ISSUE THREAD

**Issue by a5anka** [wso2/wso2-protocol-emulator#41]
- [ ] Bump maven-surefire-plugin from 2.21.0 to 2.22.2 #40
- [ ] jacoco-maven-plugin from 0.8.0 to 0.8.4 #39 
- [ ] netty.version from 4.0.52.Final to 4.1.36.Final #38
